namespace ResourceUtilities.Aseprite
{
	public enum SpriteResources
	{
		MAP_COINMAP_LAYOUT,
		MAP_TREE_BG,
		MAP_TREE_COLLISION,
		MAP_TREE_SCENE,
		OBJECT_COIN_ORANGE,
		OBJECT_COIN_RED,
		OBJECT_COIN_YELLOW,
		OBJECT_MKRAMERS_LAYER,
		OBJECT_SQUARE_COLLISION,
		OBJECT_SQUARE_SCENE
	}
}